### ISSUE TITLE
Document Android permission

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/nativescript-camera#140]
In order for this to work on Android, you must add:

```
<uses-permission android:name="android.permission.CAMERA"/>
```

While this is obvious, it really *should* be mentioned in the readme guide.

**Comment by zbranzov** [comment]
@cfjedimaster  Both demo apps are working fine on Nexus 5X Android 8.1 even though they don't have this permission added. Why do you think it is a requirement?
You can take permission via code:
```
camera.requestPermissions().then(() => {
   // you can take photos now
}).catch(() => {
   // user denied permissions
});
```

**Comment by cfjedimaster** [comment]
In my testing, when I had code that used requestPermissions, _and_ tried to take a picture, I'd see the native prompts ("app wants to blah blah"), but the catch block would fire with: [Error: Application does not have permissions to use Camera]


This is an example of what I was trying:

```
camera.requestPermissions()
.then(() => {
	camera.takePicture({ width: 300, height: 300, keepAspectRatio: true, saveToGallery:true })
	.then(imageAsset => {
		this.img = imageAsset;
	})
	.catch(e => {
		console.log('error:', e);
	});
})
.catch(e => {
	console.log('Error requesting permission');
});
```

**Comment by zbranzov** [comment]
@cfjedimaster What device do you use when it fails? 
Did you try whether demo apps cause the same error?
We are testing on android emulators and real devices using the apps from the repository and haven't seen any problem so far.

**Comment by cfjedimaster** [comment]
Device: Pixel 3 XL.
I did not try demo apps - but I've tried it in two apps so far. The one I just tried had the same error (I mean the catch block throwing).

**Comment by cfjedimaster** [comment]
Device: Pixel 3 XL.
I did not try demo apps - but I've tried it in two apps so far. The one I just tried had the same error (I mean the catch block throwing).

**Comment by cfjedimaster** [comment]
I am VERY sorry - I wrote the above comment and never hit enter.

**Comment by cfjedimaster** [comment]
Oops, or maybe I did in another tab - sorry for the noise.

**Comment by DKhalil** [comment]
@cfjedimaster hey, so there are quite a few files containing the permissions. Which file did you add it to?

**Comment by tgpetrov** [comment]
The usage of CAMERA permission is included in the aar file that is included in the plugin's 'platform/android' directory, so it is not necessary to include it in the application's manifest. 

I created a [playground](https://play.nativescript.org/?template=play-ng&id=G82tIg) with the provided code, but had no issues with the permissions when running the app. I also downloaded the playground app and was able to confirm that there is no CAMERA permission mentioned in the application's manifest file. 

Can anyone reproduce the issue with the provided playground? If so, please provide the API version of the device used for testing, since there is a [significant difference](https://android-developers.googleblog.com/2015/08/building-better-apps-with-runtime.html) in the way permissions are handled since API23 (Android 6.0).
