### ISSUE TITLE
Camera selfie mode and capture the selfie in a customized frame

### ISSUE THREAD

**Issue by Dharmendta** [NativeScript/nativescript-camera#48]
I have a screen in my app where user can upload his profile pic. whenever he opens this screen, camera should open directly in selfie mode (without any user interaction) and should allow him to take his selfie. The selfie captured by camera should be loaded in a frame for preview.

Can someone please suggest:
1) how can I load the camera to directly capture selfie?
2) how can I load the selfie captured by camera in a frame of my screen?

Thanks.

**Comment by tsonevn** [comment]
Hi @Dharmendta,
Excuse us for the delay in reply.
After a little research, we found that there is no easy way to achieve this functionality without making changes inside the nativescript-camera plugin. We will mark this as a feature request and you could keep track on the issue for further info.

**Comment by DimitarTachev** [comment]
Hi @Dharmendta,

Good news!

We recently added the **cameraFacing** option in the takePicture method. You could use it in order to set the front camera by default. It accepts either "front" or "rear" (default).

Regarding your second question, you could show the selfie everywhere in your app. Check the demo apps of the plugin for an example using the [image component](https://docs.nativescript.org/ui/images).
