### ISSUE TITLE
iOS: Strange behavior of #takePicture

### ISSUE THREAD

**Issue by Pinny3** [NativeScript/nativescript-camera#51]
Hi there,

somehow the functionality 

camera.takePicture(...)

is a little bit strange on iOS 10.3

I use the example project provided here:

https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTestAngular

When I call the functionality to take a picture in the in my app the camera comes up. Then I been prompted to allow the app to use the camera. If I denied it I still can make a photo and it's totally blacked and the photo is displayed. This is somehow strange, isn't it? Why isn't the camera closed then?

Even if I click the second time on "Take Picture" the camera comes up again allowing me to take a complete black photo...

I expect the camera to been closed once I don't allow the app to take a photo and the camera does not comes up again if I revoke the right before.

**Comment by tsonevn** [comment]
Hi @Pinny3,
Thank you for reporting this issue, 
I reviewed it on my side and was able to reproduce the same behavior while using [the non-Angular sample app](https://github.com/NativeScript/nativescript-camera/tree/master/examples/CameraTest).

For further info and a solution please keep track on the issue.

**Comment by DimitarTachev** [comment]
Hi @Pinny3,

We were relying on the camera itself to request the permission on iOS and the rejection wasn't handled properly there.

The requestPermissions method is now requesting the Camera permissions and you can easily avoid the problematic behavior by calling the `takePicture` method only when the `requestPermissions` promise is resoled. The fix is part of the [3.2.1 release ](https://github.com/NativeScript/nativescript-camera/releases/tag/v3.2.1)of the plugin.
